# Generated by Django 6.1.1 on 2026-09-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('house', models.CharField(choices=[('Lok Sabha', 'Lok Sabha'), ('Rajya Sabha', 'Rajya Sabha')], max_length=30)),
                ('introduced_by', models.CharField(max_length=150)),
                ('introduction_date', models.DateField()),
                ('status', models.CharField(choices=[('Introduced', 'Introduced'), ('Under Discussion', 'Under Discussion'), ('Passed', 'Passed'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
