# Generated by Django 6.1.1 on 2026-09-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.CharField(max_length=50, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('question_text', models.TextField()),
                ('asked_by', models.CharField(max_length=150)),
                ('house', models.CharField(choices=[('Lok Sabha', 'Lok Sabha'), ('Rajya Sabha', 'Rajya Sabha')], max_length=30)),
                ('question_type', models.CharField(choices=[('Starred', 'Starred'), ('Unstarred', 'Unstarred')], max_length=30)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Answered', 'Answered'), ('Pending', 'Pending')], max_length=30)),
                ('answer', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
