# Generated by Django 6.1.1 on 2026-09-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proceeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('house', models.CharField(max_length=50)),
                ('proceeding_date', models.DateField()),
                ('proceeding_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(default='Published', max_length=50)),
                ('document_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
