# Generated by Django 6.1.1 on 2026-09-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('Bill', 'Bill'), ('Question', 'Question'), ('Proceeding', 'Proceeding'), ('Committee', 'Committee'), ('Report', 'Report'), ('Other', 'Other')], default='Other', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('house', models.CharField(blank=True, default='', max_length=50)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('file_url', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Archived', 'Archived')], default='Available', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
