# Generated by Django 6.1.1 on 2026-09-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('house', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=100)),
                ('constituency', models.CharField(max_length=100)),
                ('party', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('education', models.CharField(blank=True, max_length=200)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('photo', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
