# Generated by Django 6.1.1 on 2026-09-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('chairperson', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=200)),
                ('house', models.CharField(choices=[('Lok Sabha', 'Lok Sabha'), ('Rajya Sabha', 'Rajya Sabha'), ('Both Houses', 'Both Houses')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=30)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
