# Generated by Django 6.1.1 on 2026-09-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='committees', to='members.member'),
        ),
    ]
